"""US production pipeline APIs.

The package root intentionally resolves exports lazily so importing one pipeline
submodule does not require every optional core/data dependency used by all other
pipelines.
"""

from __future__ import annotations

from importlib import import_module
from typing import Any


def _exports(module: str, names: tuple[str, ...]) -> dict[str, str]:
    return {name: module for name in names}


_EXPORT_MODULES: dict[str, str] = {
    **_exports(
        "microplex_us.pipelines.artifacts",
        (
            "USMicroplexArtifactPaths",
            "USMicroplexVersionedBuildArtifacts",
            "build_and_save_versioned_us_microplex",
            "build_and_save_versioned_us_microplex_from_data_dir",
            "build_and_save_versioned_us_microplex_from_source_provider",
            "build_and_save_versioned_us_microplex_from_source_providers",
            "replay_and_save_versioned_us_microplex_policyengine_stage",
            "replay_us_microplex_policyengine_stage_from_artifact",
            "save_us_microplex_artifacts",
            "save_versioned_us_microplex_artifacts",
            "save_versioned_us_microplex_build_result",
        ),
    ),
    **_exports(
        "microplex_us.pipelines.backfill_pe_native_audit",
        (
            "backfill_us_pe_native_audit_bundle",
            "backfill_us_pe_native_audit_bundles",
            "backfill_us_pe_native_audit_root",
        ),
    ),
    **_exports(
        "microplex_us.pipelines.backfill_pe_native_scores",
        (
            "backfill_us_pe_native_scores_bundle",
            "backfill_us_pe_native_scores_bundles",
            "backfill_us_pe_native_scores_root",
            "discover_us_candidate_artifact_dirs",
            "rebuild_us_pe_native_run_registry",
        ),
    ),
    **_exports(
        "microplex_us.pipelines.calibration_stage_parity",
        (
            "build_us_calibration_stage_parity_audit",
            "write_us_calibration_stage_parity_audit",
        ),
    ),
    **_exports(
        "microplex_us.pipelines.experiments",
        (
            "USMicroplexExperimentReport",
            "USMicroplexExperimentResult",
            "USMicroplexSourceExperimentSpec",
            "build_us_n_synthetic_sweep_experiments",
            "default_us_source_mix_experiments",
            "run_us_microplex_n_synthetic_sweep",
            "run_us_microplex_source_experiments",
        ),
    ),
    **_exports(
        "microplex_us.pipelines.ecps_replacement_comparison",
        (
            "build_sound_ecps_replacement_comparison",
            "write_sound_ecps_replacement_comparison",
        ),
    ),
    **_exports(
        "microplex_us.pipelines.index_db",
        (
            "append_us_microplex_run_index_entry",
            "compare_us_microplex_target_delta_rows",
            "list_us_microplex_target_delta_rows",
            "rebuild_us_microplex_run_index",
            "resolve_us_microplex_run_index_path",
            "select_us_microplex_frontier_index_row",
        ),
    ),
    **_exports(
        "microplex_us.pipelines.imputation_ablation",
        (
            "ImputationAblationReport",
            "ImputationAblationSliceSpec",
            "ImputationAblationVariant",
            "ImputationAblationVariantScore",
            "ImputationSliceScore",
            "ImputationTargetScore",
            "default_imputation_ablation_variants",
            "score_imputation_ablation_variants",
        ),
    ),
    **_exports(
        "microplex_us.pipelines.local_reweighting",
        (
            "USHouseholdTargetReweightingResult",
            "reweight_us_household_targets",
        ),
    ),
    **_exports(
        "microplex_us.pipelines.pe_native_optimization",
        (
            "PolicyEngineUSNativeWeightOptimizationResult",
            "optimize_pe_native_loss_weights",
            "optimize_policyengine_us_native_loss_dataset",
            "rewrite_policyengine_us_dataset_weights",
        ),
    ),
    **_exports(
        "microplex_us.pipelines.pe_native_scores",
        (
            "PolicyEngineUSEnhancedCPSNativeScores",
            "compare_us_pe_native_target_deltas",
            "compute_batch_us_pe_native_scores",
            "compute_policyengine_us_enhanced_cps_native_scores",
            "compute_us_pe_native_scores",
            "resolve_policyengine_us_data_python",
            "resolve_policyengine_us_data_repo_root",
            "score_policyengine_us_native_broad_loss",
            "write_us_pe_native_scores",
        ),
    ),
    **_exports(
        "microplex_us.pipelines.pe_us_data_rebuild",
        (
            "PEUSDataRebuildProgram",
            "PEUSDataRebuildStage",
            "PEUSDataRebuildStatus",
            "build_policyengine_us_data_rebuild_markdown",
            "build_policyengine_us_data_rebuild_pipeline",
            "default_policyengine_us_data_rebuild_config",
            "default_policyengine_us_data_rebuild_program",
            "default_policyengine_us_data_rebuild_source_providers",
        ),
    ),
    **_exports(
        "microplex_us.pipelines.pe_us_data_rebuild_audit",
        (
            "build_policyengine_us_data_rebuild_native_audit",
            "write_policyengine_us_data_rebuild_native_audit",
        ),
    ),
    **_exports(
        "microplex_us.pipelines.pe_us_data_rebuild_checkpoint",
        (
            "PEUSDataRebuildCheckpointEvidenceResult",
            "PEUSDataRebuildCheckpointResult",
            "attach_policyengine_us_data_rebuild_checkpoint_evidence",
            "default_policyengine_us_data_rebuild_checkpoint_config",
            "default_policyengine_us_data_rebuild_queries",
            "run_policyengine_us_data_rebuild_checkpoint",
        ),
    ),
    **_exports(
        "microplex_us.pipelines.pe_us_data_rebuild_parity",
        (
            "build_policyengine_us_data_rebuild_parity_artifact",
            "write_policyengine_us_data_rebuild_parity_artifact",
        ),
    ),
    **_exports(
        "microplex_us.pipelines.performance",
        (
            "USMicroplexPerformanceHarnessConfig",
            "USMicroplexPerformanceHarnessRequest",
            "USMicroplexPerformanceHarnessResult",
            "USMicroplexPerformanceSession",
            "run_us_microplex_performance_harness",
            "warm_us_microplex_parity_cache",
        ),
    ),
    **_exports(
        "microplex_us.pipelines.pre_sim_parity",
        (
            "DEFAULT_PRE_SIM_FOCUS_VARIABLES",
            "PreSimParityVariableSpec",
            "build_us_pre_sim_parity_audit",
            "write_us_pre_sim_parity_audit",
        ),
    ),
    **_exports(
        "microplex_us.pipelines.reduced_benchmark",
        (
            "DEFAULT_ATOMIC_AGE_BINS",
            "DEFAULT_ATOMIC_AGE_LABELS",
            "DEFAULT_ATOMIC_EMPLOYMENT_INCOME_BINS",
            "DEFAULT_ATOMIC_EMPLOYMENT_INCOME_LABELS",
            "USMicroplexReducedBenchmarkHarnessConfig",
            "USMicroplexReducedBenchmarkHarnessResult",
            "USMicroplexReducedBenchmarkReport",
            "USMicroplexReducedBenchmarkSpec",
            "USMicroplexReducedCalibrationReport",
            "USMicroplexReducedDimensionSpec",
            "USMicroplexReducedMeasureSpec",
            "USMicroplexReducedMultiCalibrationReport",
            "calibrate_and_evaluate_us_reduced_benchmark_specs",
            "calibrate_and_evaluate_us_reduced_benchmarks",
            "default_us_atomic_rung0_benchmarks",
            "default_us_atomic_rung1_benchmarks",
            "default_us_atomic_rung2_calibration",
            "default_us_atomic_rung3_calibration",
            "default_us_atomic_rung4_calibration",
            "default_us_atomic_rung5_calibration",
            "evaluate_us_reduced_benchmark",
            "reduced_benchmark_specs_to_calibration_targets",
            "reduced_benchmark_to_calibration_targets",
            "run_us_microplex_reduced_benchmark_harness",
        ),
    ),
    **_exports(
        "microplex_us.pipelines.registry",
        (
            "FrontierMetric",
            "USMicroplexRunRegistryEntry",
            "append_us_microplex_run_registry_entry",
            "build_us_microplex_run_registry_entry",
            "load_us_microplex_run_registry",
            "resolve_us_microplex_frontier_artifact_dir",
            "select_us_microplex_frontier_entry",
        ),
    ),
    **_exports(
        "microplex_us.pipelines.seed_stage_parity",
        (
            "DEFAULT_SEED_STAGE_BOOLEAN_LANDING_FEATURES",
            "DEFAULT_SEED_STAGE_CANDIDATE_ONLY_LANDING_FEATURES",
            "DEFAULT_SEED_STAGE_CATEGORICAL_LANDING_FEATURES",
            "DEFAULT_SEED_STAGE_FOCUS_VARIABLES",
            "SeedStageBooleanLandingFeatureSpec",
            "SeedStageCategoricalLandingFeatureSpec",
            "SeedStageFocusVariableSpec",
            "build_us_seed_stage_parity_audit",
            "build_us_seed_tax_unit_support_audit",
            "write_us_seed_stage_parity_audit",
            "write_us_seed_tax_unit_support_audit",
        ),
    ),
    **_exports(
        "microplex_us.pipelines.site_snapshot",
        (
            "build_us_microplex_site_snapshot",
            "write_us_microplex_site_snapshot",
        ),
    ),
    **_exports(
        "microplex_us.pipelines.stage_contracts",
        (
            "USPipelineStageContract",
            "USStageArtifactContract",
            "USStageResourceContract",
            "USStageValidationContract",
            "config_keys_for_us_pipeline_stage",
            "default_us_pipeline_stage_contracts",
            "get_us_stage_artifact_contract",
            "get_us_pipeline_stage_contract",
            "resolve_us_stage_artifact_contract_path",
            "serialize_us_pipeline_stage_contracts",
        ),
    ),
    **_exports(
        "microplex_us.pipelines.stage_artifacts",
        (
            "USCalibratedStageArtifacts",
            "USCandidateCalibrationReplayArtifacts",
            "USCandidateStageArtifacts",
            "USDatasetAssemblyArtifacts",
            "USPolicyEngineEntityStageArtifacts",
            "USSeedScaffoldStageArtifacts",
            "USStageArtifactInventory",
            "build_us_stage_artifact_inventory",
            "load_us_calibrated_stage_artifacts",
            "load_us_candidate_calibration_replay_artifacts",
            "load_us_candidate_stage_artifacts",
            "load_us_dataset_assembly_artifacts",
            "load_us_policyengine_entity_stage_artifacts",
            "load_us_seed_scaffold_stage_artifacts",
            "load_us_stage_artifact_inventory",
            "resolve_us_stage_artifact_path_checked",
            "write_us_stage_artifact_inventory",
        ),
    ),
    **_exports(
        "microplex_us.pipelines.stage_manifest",
        (
            "USDataFlowStageSummary",
            "USStageArtifactRecord",
            "USStageManifest",
            "USStageMetric",
            "USStageRecord",
            "USStageStatus",
            "USValidationEvidenceManifest",
            "USValidationEvidenceRecord",
            "build_us_validation_evidence_manifest",
            "build_us_stage_manifest",
            "load_us_policyengine_entity_stage_artifact",
            "load_us_stage_manifest",
            "resolve_us_stage_artifact_path",
            "stage_summary_for_data_flow_snapshot",
            "write_us_policyengine_entity_stage_artifact",
            "write_us_stage_manifest",
            "write_us_validation_evidence_manifest",
        ),
    ),
    **_exports(
        "microplex_us.pipelines.stage_readiness",
        (
            "USConditionalReadinessReport",
            "USConditionalReadinessStageRecord",
            "build_us_conditional_readiness_report",
            "build_us_stage_reuse_key",
            "load_us_conditional_readiness_report",
            "write_us_conditional_readiness_report",
        ),
    ),
    **_exports(
        "microplex_us.pipelines.summarize_pe_native_family_drilldown",
        (
            "classify_pe_native_target_family",
            "summarize_us_pe_native_family_drilldown",
        ),
    ),
    **_exports(
        "microplex_us.pipelines.summarize_pe_native_regressions",
        (
            "summarize_us_pe_native_regressions",
        ),
    ),
    **_exports(
        "microplex_us.pipelines.summarize_policyengine_oracle_regressions",
        (
            "summarize_us_policyengine_oracle_regressions",
        ),
    ),
    **_exports(
        "microplex_us.pipelines.summarize_policyengine_oracle_target_drilldown",
        (
            "summarize_us_policyengine_oracle_target_drilldown",
        ),
    ),
    **_exports(
        "microplex_us.pipelines.source_stage_parity",
        (
            "DEFAULT_CPS_SOURCE_STAGE_FOCUS_VARIABLES",
            "DEFAULT_PUF_SOURCE_STAGE_FOCUS_VARIABLES",
            "SourceStageParityVariableSpec",
            "build_us_cps_source_stage_parity_audit",
            "build_us_puf_source_stage_parity_audit",
            "build_us_source_stage_parity_audit",
            "observation_frame_to_policyengine_entity_bundle",
            "write_us_cps_source_stage_parity_audit",
            "write_us_puf_source_stage_parity_audit",
            "write_us_source_stage_parity_audit",
        ),
    ),
    **_exports(
        "microplex_us.pipelines.us",
        (
            "USMicroplexBuildConfig",
            "USMicroplexBuildResult",
            "USMicroplexPipeline",
            "USMicroplexTargets",
            "build_us_microplex",
        ),
    ),
}

__all__ = list(_EXPORT_MODULES)


def __getattr__(name: str) -> Any:
    """Resolve pipeline convenience exports on first access."""
    module_name = _EXPORT_MODULES.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module(module_name), name)
    globals()[name] = value
    return value
