"""US-specific adapters, targets, and pipelines for microplex."""

# ruff: noqa: E402, I001

from importlib import import_module
from typing import Any

_CALIBRATION_HARNESS_EXPORTS = (
    "CalibrationHarness",
    "CalibrationResult",
    "run_pe_parity_suite",
)
_CPS_SYNTHETIC_EXPORTS = (
    "CPSSummaryStats",
    "CPSSyntheticGenerator",
    "validate_synthetic",
)
_DATA_EXPORTS = (
    "create_sample_data",
    "get_data_info",
    "load_cps_asec",
    "load_cps_for_synthesis",
)
_GEOGRAPHY_EXPORTS = (
    "BLOCK_LEN",
    "COUNTY_LEN",
    "STATE_LEN",
    "TRACT_LEN",
    "BlockGeography",
    "derive_geographies",
    "load_block_probabilities",
    "normalize_us_state_fips",
)
_HIERARCHICAL_EXPORTS = ("prepare_cps_for_hierarchical",)
_MICROPLEX_TARGET_EXPORTS = (
    "TargetSet",
    "TargetSpec",
)
_PE_TARGETS_EXPORTS = (
    "PETargets",
    "create_calibration_targets",
    "get_pe_targets",
)

_PIPELINE_EXPORTS = (
    "DEFAULT_ATOMIC_AGE_BINS",
    "DEFAULT_ATOMIC_AGE_LABELS",
    "DEFAULT_ATOMIC_EMPLOYMENT_INCOME_BINS",
    "DEFAULT_ATOMIC_EMPLOYMENT_INCOME_LABELS",
    "FrontierMetric",
    "PEUSDataRebuildCheckpointEvidenceResult",
    "PEUSDataRebuildCheckpointResult",
    "PEUSDataRebuildProgram",
    "PEUSDataRebuildStage",
    "PEUSDataRebuildStatus",
    "USHouseholdTargetReweightingResult",
    "USMicroplexArtifactPaths",
    "USMicroplexBuildConfig",
    "USMicroplexBuildResult",
    "USMicroplexExperimentReport",
    "USMicroplexExperimentResult",
    "USMicroplexPerformanceHarnessConfig",
    "USMicroplexPerformanceHarnessRequest",
    "USMicroplexPerformanceHarnessResult",
    "USMicroplexPerformanceSession",
    "USMicroplexPipeline",
    "USMicroplexReducedBenchmarkHarnessConfig",
    "USMicroplexReducedBenchmarkHarnessResult",
    "USMicroplexReducedBenchmarkReport",
    "USMicroplexReducedBenchmarkSpec",
    "USMicroplexReducedCalibrationReport",
    "USMicroplexReducedDimensionSpec",
    "USMicroplexReducedMeasureSpec",
    "USMicroplexReducedMultiCalibrationReport",
    "USMicroplexRunRegistryEntry",
    "USMicroplexSourceExperimentSpec",
    "USMicroplexTargets",
    "USMicroplexVersionedBuildArtifacts",
    "backfill_us_pe_native_audit_bundle",
    "backfill_us_pe_native_audit_bundles",
    "backfill_us_pe_native_audit_root",
    "backfill_us_pe_native_scores_bundle",
    "backfill_us_pe_native_scores_bundles",
    "backfill_us_pe_native_scores_root",
    "append_us_microplex_run_index_entry",
    "append_us_microplex_run_registry_entry",
    "attach_policyengine_us_data_rebuild_checkpoint_evidence",
    "build_and_save_versioned_us_microplex",
    "build_and_save_versioned_us_microplex_from_data_dir",
    "build_and_save_versioned_us_microplex_from_source_provider",
    "build_and_save_versioned_us_microplex_from_source_providers",
    "build_policyengine_us_data_rebuild_markdown",
    "build_policyengine_us_data_rebuild_native_audit",
    "build_policyengine_us_data_rebuild_pipeline",
    "build_us_microplex",
    "build_us_microplex_run_registry_entry",
    "build_us_microplex_site_snapshot",
    "calibrate_and_evaluate_us_reduced_benchmark_specs",
    "calibrate_and_evaluate_us_reduced_benchmarks",
    "compare_us_microplex_target_delta_rows",
    "default_policyengine_us_data_rebuild_checkpoint_config",
    "default_policyengine_us_data_rebuild_config",
    "default_policyengine_us_data_rebuild_program",
    "default_policyengine_us_data_rebuild_queries",
    "default_policyengine_us_data_rebuild_source_providers",
    "default_us_atomic_rung0_benchmarks",
    "default_us_atomic_rung1_benchmarks",
    "default_us_atomic_rung2_calibration",
    "default_us_atomic_rung3_calibration",
    "default_us_atomic_rung4_calibration",
    "default_us_atomic_rung5_calibration",
    "default_us_source_mix_experiments",
    "evaluate_us_reduced_benchmark",
    "discover_us_candidate_artifact_dirs",
    "list_us_microplex_target_delta_rows",
    "load_us_microplex_run_registry",
    "rebuild_us_microplex_run_index",
    "reduced_benchmark_specs_to_calibration_targets",
    "reduced_benchmark_to_calibration_targets",
    "resolve_us_microplex_frontier_artifact_dir",
    "resolve_us_microplex_run_index_path",
    "reweight_us_household_targets",
    "run_policyengine_us_data_rebuild_checkpoint",
    "run_us_microplex_performance_harness",
    "run_us_microplex_reduced_benchmark_harness",
    "run_us_microplex_source_experiments",
    "save_us_microplex_artifacts",
    "save_versioned_us_microplex_artifacts",
    "save_versioned_us_microplex_build_result",
    "select_us_microplex_frontier_entry",
    "select_us_microplex_frontier_index_row",
    "warm_us_microplex_parity_cache",
    "write_policyengine_us_data_rebuild_native_audit",
    "write_us_microplex_site_snapshot",
    "rebuild_us_pe_native_run_registry",
)

_POLICYENGINE_EXPORTS = (
    "PolicyEngineUSComparisonCache",
    "PolicyEngineUSConstraint",
    "PolicyEngineUSDBTarget",
    "PolicyEngineUSDBTargetProvider",
    "PolicyEngineUSEntityTableBundle",
    "PolicyEngineUSMicrosimulationAdapter",
    "PolicyEngineUSQuantityTarget",
    "PolicyEngineUSTargetComparisonReport",
    "PolicyEngineUSTargetEvaluation",
    "PolicyEngineUSTargetEvaluationReport",
    "PolicyEngineUSVariableBinding",
    "build_policyengine_us_export_column_names",
    "build_policyengine_us_time_period_arrays",
    "compare_policyengine_us_target_query_to_baseline",
    "compile_policyengine_us_household_linear_constraints",
    "compute_policyengine_us_definition_hash",
    "detect_policyengine_pseudo_inputs",
    "evaluate_policyengine_us_target_query",
    "evaluate_policyengine_us_target_set",
    "filter_supported_policyengine_us_targets",
    "infer_policyengine_us_variable_bindings",
    "load_policyengine_us_entity_tables",
    "materialize_policyengine_us_variables",
    "policyengine_us_formula_variables_for_targets",
    "policyengine_us_variables_to_materialize",
    "project_frame_to_time_period_arrays",
    "write_policyengine_us_time_period_dataset",
)
_SOURCE_REGISTRY_EXPORTS = (
    "DEFAULT_SOURCE_VARIABLE_POLICIES",
    "PUF_SOURCE_VARIABLE_POLICY",
    "SourceVariablePolicy",
    "SourceVariablePolicySpec",
    "resolve_source_variable_capabilities",
)
_TARGET_REGISTRY_EXPORTS = (
    "TargetCategory",
    "TargetGroup",
    "TargetLevel",
    "TargetRegistry",
    "get_registry",
    "print_registry_summary",
)
_TARGETS_EXPORTS = (
    "POLICYENGINE_US_COUNT_ENTITIES",
    "policyengine_db_target_to_canonical_spec",
    "policyengine_db_targets_to_canonical_set",
)
_UNIFIED_CALIBRATION_EXPORTS = (
    "CalibrationTarget",
    "UnifiedCalibrator",
    "calibrate_to_pe_targets",
)
_VALIDATION_EXPORTS = (
    "AGI_BRACKETS",
    "FILING_STATUSES",
    "BaselineComparison",
    "MetricComparison",
    "SOITargets",
    "ValidationResult",
    "compute_baseline_comparison",
    "compute_validation_metrics",
    "export_comparison_json",
    "get_soi_years",
    "load_soi_targets",
    "validate_against_soi",
)

_LAZY_EXPORT_MODULES: dict[str, str] = {
    **dict.fromkeys(_CALIBRATION_HARNESS_EXPORTS, "microplex_us.calibration_harness"),
    **dict.fromkeys(_CPS_SYNTHETIC_EXPORTS, "microplex_us.cps_synthetic"),
    **dict.fromkeys(_DATA_EXPORTS, "microplex_us.data"),
    **dict.fromkeys(_GEOGRAPHY_EXPORTS, "microplex_us.geography"),
    **dict.fromkeys(_HIERARCHICAL_EXPORTS, "microplex_us.hierarchical"),
    **dict.fromkeys(_MICROPLEX_TARGET_EXPORTS, "microplex.targets"),
    **dict.fromkeys(_PE_TARGETS_EXPORTS, "microplex_us.pe_targets"),
    **dict.fromkeys(_PIPELINE_EXPORTS, "microplex_us.pipelines"),
    **dict.fromkeys(_POLICYENGINE_EXPORTS, "microplex_us.policyengine"),
    **dict.fromkeys(_SOURCE_REGISTRY_EXPORTS, "microplex_us.source_registry"),
    **dict.fromkeys(_TARGET_REGISTRY_EXPORTS, "microplex_us.target_registry"),
    **dict.fromkeys(_TARGETS_EXPORTS, "microplex_us.targets"),
    **dict.fromkeys(_UNIFIED_CALIBRATION_EXPORTS, "microplex_us.unified_calibration"),
    **dict.fromkeys(_VALIDATION_EXPORTS, "microplex_us.validation"),
}
_OPTIONAL_NONE_EXPORTS = frozenset((*_GEOGRAPHY_EXPORTS, *_VALIDATION_EXPORTS))


def __getattr__(name: str) -> Any:
    """Resolve optional heavyweight convenience exports on first access."""
    module_name = _LAZY_EXPORT_MODULES.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    try:
        value = getattr(import_module(module_name), name)
    except ImportError:
        if name not in _OPTIONAL_NONE_EXPORTS:
            raise
        value = None
    globals()[name] = value
    return value


__all__ = [
    "CalibrationHarness",
    "CalibrationResult",
    "run_pe_parity_suite",
    "PETargets",
    "create_calibration_targets",
    "get_pe_targets",
    "USMicroplexArtifactPaths",
    "FrontierMetric",
    "PEUSDataRebuildCheckpointEvidenceResult",
    "PEUSDataRebuildCheckpointResult",
    "PEUSDataRebuildProgram",
    "PEUSDataRebuildStage",
    "PEUSDataRebuildStatus",
    "USMicroplexRunRegistryEntry",
    "USMicroplexBuildConfig",
    "USMicroplexBuildResult",
    "USMicroplexPipeline",
    "attach_policyengine_us_data_rebuild_checkpoint_evidence",
    "build_policyengine_us_data_rebuild_pipeline",
    "build_policyengine_us_data_rebuild_native_audit",
    "default_policyengine_us_data_rebuild_checkpoint_config",
    "default_policyengine_us_data_rebuild_config",
    "default_policyengine_us_data_rebuild_queries",
    "default_policyengine_us_data_rebuild_source_providers",
    "append_us_microplex_run_index_entry",
    "append_us_microplex_run_registry_entry",
    "compare_us_microplex_target_delta_rows",
    "USMicroplexTargets",
    "USMicroplexVersionedBuildArtifacts",
    "USMicroplexExperimentReport",
    "USMicroplexExperimentResult",
    "USMicroplexSourceExperimentSpec",
    "USMicroplexPerformanceHarnessConfig",
    "USMicroplexPerformanceHarnessRequest",
    "USMicroplexPerformanceHarnessResult",
    "USMicroplexPerformanceSession",
    "USMicroplexReducedCalibrationReport",
    "USMicroplexReducedMultiCalibrationReport",
    "USMicroplexReducedBenchmarkHarnessConfig",
    "USMicroplexReducedBenchmarkHarnessResult",
    "USMicroplexReducedBenchmarkReport",
    "USMicroplexReducedBenchmarkSpec",
    "USMicroplexReducedDimensionSpec",
    "USMicroplexReducedMeasureSpec",
    "USHouseholdTargetReweightingResult",
    "DEFAULT_ATOMIC_AGE_BINS",
    "DEFAULT_ATOMIC_AGE_LABELS",
    "DEFAULT_ATOMIC_EMPLOYMENT_INCOME_BINS",
    "DEFAULT_ATOMIC_EMPLOYMENT_INCOME_LABELS",
    "default_us_atomic_rung0_benchmarks",
    "default_us_atomic_rung1_benchmarks",
    "default_us_atomic_rung2_calibration",
    "default_us_atomic_rung3_calibration",
    "default_us_atomic_rung4_calibration",
    "default_us_atomic_rung5_calibration",
    "default_policyengine_us_data_rebuild_program",
    "default_us_source_mix_experiments",
    "build_and_save_versioned_us_microplex",
    "build_and_save_versioned_us_microplex_from_data_dir",
    "build_and_save_versioned_us_microplex_from_source_provider",
    "build_and_save_versioned_us_microplex_from_source_providers",
    "build_policyengine_us_data_rebuild_markdown",
    "build_us_microplex",
    "build_us_microplex_run_registry_entry",
    "load_us_microplex_run_registry",
    "list_us_microplex_target_delta_rows",
    "rebuild_us_microplex_run_index",
    "calibrate_and_evaluate_us_reduced_benchmark_specs",
    "calibrate_and_evaluate_us_reduced_benchmarks",
    "reweight_us_household_targets",
    "resolve_us_microplex_frontier_artifact_dir",
    "resolve_us_microplex_run_index_path",
    "evaluate_us_reduced_benchmark",
    "reduced_benchmark_to_calibration_targets",
    "reduced_benchmark_specs_to_calibration_targets",
    "run_policyengine_us_data_rebuild_checkpoint",
    "write_policyengine_us_data_rebuild_native_audit",
    "run_us_microplex_performance_harness",
    "run_us_microplex_reduced_benchmark_harness",
    "run_us_microplex_source_experiments",
    "save_us_microplex_artifacts",
    "save_versioned_us_microplex_build_result",
    "build_us_microplex_site_snapshot",
    "select_us_microplex_frontier_index_row",
    "save_versioned_us_microplex_artifacts",
    "select_us_microplex_frontier_entry",
    "write_us_microplex_site_snapshot",
    "warm_us_microplex_parity_cache",
    "PolicyEngineUSConstraint",
    "PolicyEngineUSComparisonCache",
    "PolicyEngineUSDBTarget",
    "PolicyEngineUSDBTargetProvider",
    "PolicyEngineUSEntityTableBundle",
    "PolicyEngineUSMicrosimulationAdapter",
    "PolicyEngineUSQuantityTarget",
    "PolicyEngineUSTargetComparisonReport",
    "PolicyEngineUSTargetEvaluation",
    "PolicyEngineUSTargetEvaluationReport",
    "PolicyEngineUSVariableBinding",
    "build_policyengine_us_export_column_names",
    "build_policyengine_us_time_period_arrays",
    "compare_policyengine_us_target_query_to_baseline",
    "compile_policyengine_us_household_linear_constraints",
    "compute_policyengine_us_definition_hash",
    "detect_policyengine_pseudo_inputs",
    "evaluate_policyengine_us_target_query",
    "evaluate_policyengine_us_target_set",
    "filter_supported_policyengine_us_targets",
    "infer_policyengine_us_variable_bindings",
    "load_policyengine_us_entity_tables",
    "materialize_policyengine_us_variables",
    "policyengine_us_formula_variables_for_targets",
    "policyengine_us_variables_to_materialize",
    "project_frame_to_time_period_arrays",
    "write_policyengine_us_time_period_dataset",
    "SourceVariablePolicy",
    "SourceVariablePolicySpec",
    "PUF_SOURCE_VARIABLE_POLICY",
    "DEFAULT_SOURCE_VARIABLE_POLICIES",
    "resolve_source_variable_capabilities",
    "CalibrationTarget",
    "UnifiedCalibrator",
    "calibrate_to_pe_targets",
    "CPSSummaryStats",
    "CPSSyntheticGenerator",
    "validate_synthetic",
    "load_cps_asec",
    "load_cps_for_synthesis",
    "create_sample_data",
    "get_data_info",
    "BlockGeography",
    "load_block_probabilities",
    "derive_geographies",
    "normalize_us_state_fips",
    "prepare_cps_for_hierarchical",
    "STATE_LEN",
    "COUNTY_LEN",
    "TRACT_LEN",
    "BLOCK_LEN",
    "TargetRegistry",
    "TargetSpec",
    "TargetSet",
    "TargetCategory",
    "TargetLevel",
    "TargetGroup",
    "get_registry",
    "print_registry_summary",
    "POLICYENGINE_US_COUNT_ENTITIES",
    "policyengine_db_target_to_canonical_spec",
    "policyengine_db_targets_to_canonical_set",
    "AGI_BRACKETS",
    "FILING_STATUSES",
    "SOITargets",
    "get_soi_years",
    "load_soi_targets",
    "compute_validation_metrics",
    "ValidationResult",
    "validate_against_soi",
    "MetricComparison",
    "BaselineComparison",
    "compute_baseline_comparison",
    "export_comparison_json",
]
